apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryapp
  template:
    metadata:
      labels:
        app: inventoryapp
    spec:
      containers:
        - name: inventory-container
          image: tipu247/inventoryservice:v1
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: asp-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: asp-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: asp-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: asp-secret
                  key: DB_PASSWORD

---

# ========================
# Service for ASP.NET App
# ========================
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventoryapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
