apiVersion: v1
kind: Secret
metadata:
  name: asp-secret
  namespace: aspnetapp
type: Opaque
stringData:
  DB_PASSWORD: "Tipu@123"
  MYSQL_ROOT_PASSWORD: "root@123"
  MYSQL_USER: "Tipu"
  MYSQL_PASSWORD: "Tipu@123"
  MYSQL_DATABASE: "accountingDb"
